export const CBSE_VIII_QUESTIONS = [
    { id: 'VIII CBSE-1', text: 'What are the different steps involved in agricultural practices? Explain any two.' },
    { id: 'VIII CBSE-2', text: 'What is the difference between manure and fertilizers?' },
    { id: 'VIII CBSE-3', text: 'How do microorganisms benefit humans in daily life?' },
    { id: 'VIII CBSE-4', text: 'Explain how some microorganisms are harmful and cause diseases in humans, plants, or animals.' },
    { id: 'VIII CBSE-5', text: 'Why is the nitrogen cycle important for the environment?' },
    { id: 'VIII CBSE-6', text: 'Explain the process of fossil fuel formation.' },
    { id: 'VIII CBSE-7', text: 'What are the essential conditions required for combustion to take place?' },
    { id: 'VIII CBSE-8', text: 'Draw a neat diagram of a candle flame and label its different zones.' },
    { id: 'VIII CBSE-9', text: 'What are the major causes of deforestation and its consequences?' },
    { id: 'VIII CBSE-10', text: 'Why is the conservation of biodiversity essential for our ecosystem?' },
    { id: 'VIII CBSE-11', text: 'Differentiate between sexual and asexual reproduction in animals.' },
    { id: 'VIII CBSE-12', text: 'Describe the process of fertilization in humans.' },
    { id: 'VIII CBSE-13', text: 'What is the role of hormones in reaching the age of adolescence?' },
    { id: 'VIII CBSE-14', text: 'Explain the changes that occur in the human body during puberty.' },
    { id: 'VIII CBSE-15', text: 'Explain the difference between contact and non-contact forces with examples.' },
    { id: 'VIII CBSE-16', text: 'Why is friction sometimes considered a necessary evil?' },
    { id: 'VIII CBSE-17', text: 'How can we reduce or increase friction in different situations?' },
    { id: 'VIII CBSE-18', text: 'Explain how sound is produced and what factors affect its loudness and pitch.' },
    { id: 'VIII CBSE-19', text: 'What are the chemical effects of electric current? Give one practical example.' },
    { id: 'VIII CBSE-20', text: 'State the laws of reflection and describe the characteristics of an image formed by a plane mirror.' }
];

export const NEET_QUESTIONS = [
    { id: 'NEET-1', text: 'Calculate the phenotypic and genotypic ratios in monohybrid and dihybrid crosses based on Mendel`s laws.' },
    { id: 'NEET-2', text: 'Explain the enzymes involved in DNA Replication (DNA polymerase, helicase, ligase) and the direction of replication.' },
    { id: 'NEET-3', text: 'How do you calculate allele and genotype frequencies in a population using the Hardy-Weinberg Equilibrium principle?' },
    { id: 'NEET-4', text: 'Describe the process of protein synthesis, including the role of tRNA, mRNA, and ribosomes during transcription and translation.' },
    { id: 'NEET-5', text: 'What are the core properties of the genetic code, and what are point mutations?' },
    { id: 'NEET-6', text: 'Detail the sequential events of the cardiac cycle and how they correlate to ECG interpretation.' },
    { id: 'NEET-7', text: 'Explain the mechanisms of urine formation in a nephron, including the counter-current mechanism.' },
    { id: 'NEET-8', text: 'Discuss the roles of various endocrine glands and outline their feedback mechanisms for hormonal regulation.' },
    { id: 'NEET-9', text: 'Define respiratory volumes, providing normal values for tidal volume, vital capacity, and residual volume.' },
    { id: 'NEET-10', text: 'Describe the conduction of nerve impulses and explain the detailed structure of a synapse.' },
    { id: 'NEET-11', text: 'Outline the sequential process of spermatogenesis and oogenesis (Gametogenesis).' },
    { id: 'NEET-12', text: 'Explain the hormonal changes and phases (follicular, luteal, etc.) defining the human menstrual cycle.' },
    { id: 'NEET-13', text: 'Compare and contrast key Assisted Reproductive Technologies (ART) like IVF, ZIFT, GIFT, and IUI.' },
    { id: 'NEET-14', text: 'What are the critical steps in recombinant DNA technology involving restriction enzymes and vectors?' },
    { id: 'NEET-15', text: 'Explain the fundamental principles and applications of PCR and Gel Electrophoresis.' },
    { id: 'NEET-16', text: 'Compare Mitosis and Meiosis emphasizing differences in their stages, significance, and cellular outcomes.' },
    { id: 'NEET-17', text: 'Contrast the functions of mitochondria, chloroplasts, ribosomes, and the endomembrane system in eukaryotic cells.' },
    { id: 'NEET-18', text: 'Provide distinct examples for ecological population interactions including: mutualism, predation, competition, commensalism, and parasitism.' },
    { id: 'NEET-19', text: 'Differentiate between ecological pyramids of energy, biomass, and numbers, identifying scenarios when they are inverted.' },
    { id: 'NEET-20', text: 'Outline the differences between dicot and monocot plant anatomy, including root, stem, and leaf structures.' }
];
